name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run black check
        run: black --diff --check api/ handlers/

      - name: Run isort check
        run: isort --check-only --profile black api/ handlers/

      - name: Run flake8
        run: flake8 api/ handlers/
